version: "3.8"
services:
  postgres:
    image: postgres:10-alpine3.16
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rating_service
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d rating_service -U postgres" ]
      interval: 15s
      timeout: 60s
      retries: 5
      start_period: 80s

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'

  rating-service:
    build:
      context: prontopro
      dockerfile: ./rating_service/Dockerfile_rating_service
    ports:
      - "7000:7000"
    environment:
      - DATASOURCE=host=postgres user=postgres password=postgres dbname=rating_service port=5432
      - PORT=7000
    depends_on:
        postgres:
          condition: service_healthy


  notification-service:
    build:
      context: prontopro
      dockerfile: ./rating_service/Dockerfile_notification_service
    ports:
      - "7001:7001"
    environment:
      - DATASOURCE=host=postgres user=postgres password=postgres dbname=rating_service port=5432
      - PORT=7001
      - REDIS_URL=redis:6379
    depends_on:
      postgres:
        condition: service_healthy